### ISSUE TITLE
/usr/local/bin/polkadot-js-api: Argument list too long

### ISSUE THREAD

**Issue by coriolinus** [polkadot-js/tools#104]
I'm attempting to use the new sudo feature to submit a parachain registration; the invocation is pretty simple:

```sh
hex_of () {
    xxd -p "$1" | tr -d $'\n' | sed 's/^/0x&/'
}

polkadot-js-api \
    --ws ws://172.28.1.1:9944 \
    --sudo \
    --seed "//Alice" \
    tx.registrar.registerPara \
        100 \
        '{"scheduling":"Always"}' \
        "$(hex_of /runtime/cumulus_test_parachain_runtime.compact.wasm)" \
        "$(hex_of /genesis/genesis-state)"
```

Unfortunately, this fails, probably due to argument parsing restrictions:

```
$ docker logs cumulus_registrar_1
Tue 18 Feb 2020 03:37:54 PM CET
/usr/bin/register_para.sh: line 12: /usr/local/bin/polkadot-js-api: Argument list too long
```

Given that the test runtime is ~0.5Mb in binary form, I'm not entirely surprised that the argument parser gives up on it.

**Comment by jacogr** [comment]
@kwingram25 Added the read-all-tx-params from a file specifically for this case - https://github.com/polkadot-js/tools/pull/91

**Comment by coriolinus** [comment]
Oh, that's not bad. It still requires assembling a temporary file with everything in it.

What would you think of adding magic syntax like this?

```sh
polkadot-js-api \
    --ws ws://172.28.1.1:9944 \
    --sudo \
    --seed "//Alice" \
    tx.registrar.registerPara \
        100 \
        '{"scheduling":"Always"}' \
        @/runtime/cumulus_test_parachain_runtime.compact.wasm \
        @/genesis/genesis-state
```

**Comment by jacogr** [comment]
The only thing with the above is that it needs to know the type of input. However if we always assume (for magic syntax) that is is bytes, that could work -

- read file into Uint8Array
- convert to hex (this will be important, since otherwise it will expect a length prefix)

**Comment by coriolinus** [comment]
Yeah, I think that's a reasonable assumption. I'll start working on that PR.
