### ISSUE TITLE
Error: Metadata:: Number can only safely store up to 53 bits

### ISSUE THREAD

**Issue by ltfschoen** [polkadot-js/tools#13]
I get the following error when I run any of the examples `yarn run:api query.substrate.code --info`. I've tried using different Node.js versions 10.7.0, 10.15.0, 11.9.
```
$ yarn run:api query.substrate.code --info
yarn run v1.10.1
$ ./packages/api-cli/src/index.js query.substrate.code --info
2019-03-27 19:30:18        RPC-CORE: getMetadata (block: Hash): Metadata:: Number can only safely store up to 53 bits
2019-03-27 19:30:18   API/DECORATOR: loadMeta ExtError: getMetadata (block: Hash): Metadata:: Number can only safely store up to 53 bits
    at Object.call [as getMetadata] (/Users/me/code/src/polkadot-js/tools/node_modules/@polkadot/rpc-core/index.js:136:15)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by jacogr** [comment]
Sadly the API packages are outdated in this repo - there are only so many hours in a day.

**Comment by ltfschoen** [comment]
@jacogr I'm still encountering this issue even updating to the latest master

**Comment by jacogr** [comment]
So, `-beta` (as with all repos) are published to the `@beta` channel until a release is made, i.e. all in the dep tree are deemed "stable".

See latest & beta here under versions - https://www.npmjs.com/package/@polkadot/api-cli

So if you want to try the latest master as pushed, that is `0.3.0-beta.3`, or `npm install -g @polkadot/api-cli@beta` (What you are doing above is not actually running master, you are running that last published/latest version which is still the problematic one)

**Comment by jacogr** [comment]
0.3.1 (stable) tagged in https://github.com/polkadot-js/tools/pull/21, will be published as CI completes
