### ISSUE TITLE
is secure enough to use polkadot-js-api --seed "$1" tx.staking.bond address .... --ws wss://rpc.polkadot.io

### ISSUE THREAD

**Issue by carltraveler** [polkadot-js/tools#159]
hi guys:
      I do not have expirence wiht nodejs.  --seed need the private key. is that have any risk exposure the seed to anyone on the net tried to listening

**Comment by jacogr** [comment]
It doesn't get sent over the network. It is used for signing locally. (keypair gets created in-memory, with a non-secret accessible interface, it handles signing)

**Comment by carltraveler** [comment]
ok. so I can trust. however as the #82  issue refered.  input the seed on console is dangers. save both in command line history and console history. may need a better choice

**Comment by carltraveler** [comment]
can tx.staking.bondExtra add bonded money to get more interest?

**Comment by jacogr** [comment]
If you have 1000 Tokens,

- call bond on 750, it means you have 250 left (750 bonded, 250 free)
- now you can call bondExtra with 125 and have 875 bonded and 125 free

**Comment by carltraveler** [comment]
thanks.  and I try to bondExtra success before. but with the same command get the error "wasm runtime unreachale". is that the network unreachable reason?  and I checked the explore of substrate scan. the tx do not send out.

**Comment by jacogr** [comment]
That is from the node. Honestly have not seen that specific one before, so have no idea as to what it struggles with.

**Comment by carltraveler** [comment]
ok. thanks again. anthor more question. how can i use polkdot-js-api to create a tx and  sign a bondExtra/transfer then send out the tx. I try to use `polkadot-js-api signer --ws xxx balances.transfer --account xxx yyy 123 ` to create a a tx like https://github.com/polkadot-js/tools/tree/master/packages/signer-cli this guide mention. but failed. any thing wrong?

**Comment by carltraveler** [comment]
I still want my seed do not touch any web env. so try to do this

**Comment by jacogr** [comment]
Always ensure the number is fully specified, i.e. the cli tool has no idea of on-chain decimals. So (taking Polkadot, since it is simpler with 10 decimals) and amount of "123" will transfer "0.000 000 0123 DOT" while 12300000000 would transfer 1.23 DOT.

**Comment by carltraveler** [comment]
thanks very much. I have solve my problem.
