### ISSUE TITLE
add staking/delegation tx

### ISSUE THREAD

**Issue by roccomuso** [polkadot-js/tools#169]
Would be useful to add staking transaction support to `@polkadot/signer-cli`

**Comment by jacogr** [comment]
What do you believe is missing? You can pass any JSON object as params and that will be parsed into a transaction by the API. Since this a a low-level tool, you need to understand which object to construct. (Which is the same as what Rust expects)

**Comment by roccomuso** [comment]
I thought it was missing, 'cause I didn't see an example on the README

**Comment by jacogr** [comment]
The thing to remember about Substrate is that is is exceptionally flexible, there is no one-size-fits-all.

So some chains have democracy, some chains don't (like Westend). Some chains have staking, some chains don't (like Kulupu). Some chains have transfers, and some chains (like Acala) doesn't.

All this is provided by the metadata. All the signer-cli does is use the transactions exposed by the chain metadata and construct transactions based on that. So if it is available on chain, it is in the metadata and it will be available via the cli.

**Comment by roccomuso** [comment]
gotcha, but this package is specifically for Polkadot chain, isn't it?

**Comment by jacogr** [comment]
No, it supports any Substrate-based chain. (Like the polkadot-js API, the apps UI, the extension, etc.)

**Comment by joelamouche** [comment]
@roccomuso Have you tried using it for a parachain?
