### ISSUE TITLE
Unable to match provided value to a secret URI

### ISSUE THREAD

**Issue by robin-crypto-com** [polkadot-js/tools#174]
Hello,

I'm trying to use the [signer-cli](https://github.com/polkadot-js/tools/tree/master/packages/signer-cli),
but it fails with `Error: Unable to match provided value to a secret URI` so I'm wondering if it's my seed problem ?
I find it weird given that I'm locally able to use this seed to generate a keyring pair -> create tx -> sign -> send

```
const keyringPair = (new Keyring()).addFromUri("12345678901234567890123456789012"); // suri length 32
// address from this keyring pair = 5FA9nQDVg267DEd8m1ZypXLBnvN7SFxYwV7ndqSYGiN9TTpu
...
const transferMethod = api.tx.balances.transfer(destinationAddress, amount);
const payload = createType(nodeApi.registry, 'SignerPayload', {
	method: transferMethod,
	nonce,
	genesisHash: api.genesisHash,
	blockHash: api.genesisHash,
	runtimeVersion: api.runtimeVersion,
	version: api.extrinsicVersion,
}).toPayload();
const extrinsic = createType(api.registry, "ExtrinsicPayload", payload, { version: payload.version });
const hex = extrinsic.toHex();
...
```

in my terminal:
```
polkadot-js-signer sign --account 5FA9nQDVg267DEd8m1ZypXLBnvN7SFxYwV7ndqSYGiN9TTpu --seed "12345678901234567890123456789012" --type ed25519 "...extrinsic-hex..."
```

**Comment by jacogr** [comment]
Prefix all hex values (here and in the API, UIs, etc) with `0x`.

**Comment by robin-crypto-com** [comment]
It seems it needs to be mnemonic then
adding `0x` in front of my seed gives me `Error: Hex seed needs to be 256-bits`

Is there a way to generate a mnemonic corresponding to my seed ?

**Comment by jacogr** [comment]
Yes, `0x12345678901234567890123456789012` is only 128 bits. (256 bits in 64 characters, excluding `0x`)

No, you cannot go from mini secret to mnemonic (it is a one-way operation).

**Comment by robin-crypto-com** [comment]
Oh ok perfect, it works fine now with `0x + 64 characters seed`
Many thanks again 🙏

**Comment by robin-crypto-com** [comment]
In the end I didn't use the signer-cli directly, I just got this piece of code from it:
```
import { hexToU8a, u8aToHex, u8aConcat } from "@polkadot/util";
const payloadU8a = hexToU8a(extrinsicPayload.toHex());
const signatureU8a = fromKeysPair.sign(payloadU8a);
const prefix = new Uint8Array([0]); // corresponds to keyring type ed25519
const signatureU8aWithPrefix = u8aConcat(prefix, _signatureU8a);
const signature = u8aToHex(signatureU8aWithPrefix);
```
I would suggest to promote that to the polkadot-js/api documentation, it may be useful in some cases.

**Comment by jacogr** [comment]
The API FAQ does point here. (And also ty wrapper). It is simple enough as a sample that shows both sides to just keep that in place. 

Glad you got sorted.

**Comment by robin-crypto-com** [comment]
Now I have another problem though, the signature returned by the signer-cli is different than the one I get with my previous code:
```
...
const myKeyringPair = (new Keyring({ type: "ed25519" })).createFromUri("0x12...34");
...
// build
const transfer = api.tx.balances.transfer(destinationAddress, amount);
const signerPayload = createType(api.registry, 'SignerPayload', {
	method: transfer,
	nonce: String(nonce),
	genesisHash: api.genesisHash,
	blockHash: api.genesisHash,
	runtimeVersion: api.runtimeVersion,
	version: api.extrinsicVersion,
});
const extrinsicPayload = createType(api.registry, "ExtrinsicPayload", signerPayload.toPayload(), { version: signerPayload.version });

// sign
const { signature } = extrinsicPayload.sign(myKeyringPair);

// send
transfer.addSignature(myAddress, signature, signerPayload.toPayload());
await transfer.send();
```
signature is different here:
```
polkadot-js-signer sign --account "...myAddress..." --seed "0x12...34" --type ed25519 "...extrinsicPayload.toHex()..."
```
and using it for `addSignature` then send will give me the error:
`RPC-CORE: submitExtrinsic(extrinsic: Extrinsic): Hash:: 1010: Invalid Transaction: Transaction has a bad signature`
