### ISSUE TITLE
empty payload error

### ISSUE THREAD

**Issue by jaslin-W** [polkadot-js/tools#188]
i run this command. But this a error
`yarn run:signer sign --account 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY --seed "0xe5be9a5092b81bca64be81d212e7f2f9eba183bb7a90954f7b76361f6edb5c0a" --type sr25519 0x05008eaf04151687736326c9fea17e25fc5287613693c912909cb226aa4794f26a48ed01950214001a000000050000000daa0b8ae7b59f772c9`

![zxczxczxc](https://user-images.githubusercontent.com/65018397/100341355-69a90e00-3017-11eb-9962-aa1952bd5322.png)

**Comment by jacogr** [comment]
Closing, fixed in https://github.com/polkadot-js/tools/pull/208
