### ISSUE TITLE
Use Signer-CLI with hex-encoded key

### ISSUE THREAD

**Issue by joepetrowski** [polkadot-js/tools#207]
A user is trying to use Signer CLI with a hex-encoded key rather than mnemonic.

- Is signer-cli able to accept hex keys?
- If no, is it possible to add?

**Comment by jacogr** [comment]
IT should be quick if not already available... lemme check.

**Comment by pavelrib** [comment]
Is this a correct usage?
```
polkadot-js-signer sign --account <polkadot ss58 account starting with 1> --seed <private_key_hex> --type ed25519 0x0500c8deea5a67504d644b16bf91b733b9b89a5ae1a9a067ee9a8fe03f6e9c9e3f520700e40b5402250210001a0000000500000091b171bb158e2d3848fa23a9f1c25182fb8e20313b2c1eb49219da7a70ce90c3fc03954d8f67fa645ae4fecb0d5541b6c17a1afe166c1353c9494652c28fcede
```
I get:
`Error: Payload must be supplied as a hex string. Please check your input and try again.`

**Comment by jacogr** [comment]
Yes, should really work just do `--seed "0x12345..." --payload "0x...."` - would just add "'s around the payload as well, it looks correct but the CLI sometimes does do weird things.

**Comment by pavelrib** [comment]
Added "'s around everything I could, still throws this error. 
Which version of nvm does this supposed to work in? I'm using 14.15.1.

**Comment by jacogr** [comment]
Ummmm... Ok, lemme check it out, where there is smoke, there is fire.

**Comment by jacogr** [comment]
Update - indeed. for some reason the yargs parser now tries to be clever and parses the hex (even if quoted) into a number. Will get a fix in and release a patch.

For the meantime there is a work-around for the payload by passing a file, however I'm afraid it will probably parse the hex seed into a number as well. So needs a fix. The only good news is that there are work-arounds for this same thing elsewhere, so it will be quite to bring in.

Will look now.

**Comment by pavelrib** [comment]
@jacogr Thanks for fixing this.
I'm not sure what you mean by the workaround you've mentioned. How do I pass a file?

**Comment by jacogr** [comment]
You can pass hex ;)

The file I don’t think is 100% for the payload context as it stands. It expects a binary file, not a hex. (So it works great in eg. the api-cli where you for instance want to submit an upgrade)

Here not so much since you would just through hoops as it is implemented to first convert to binary and then add it... horrible. 

 But anyway the syntax is “@<path goes here>”. If there is need can extend it to cater for hex contents as well - but as it stands my workaround above is probably worse.

**Comment by pavelrib** [comment]
Thanks, that indeed did the trick. However I now have a bad signature error. Posted in other open issue, don't know whether it's related.
