### ISSUE TITLE
Error: Cannot find module './cli.cjs'

### ISSUE THREAD

**Issue by sriney-staked** [polkadot-js/tools#236]
node v15.5.0

`yarn install` results in
```yarn install v1.15.2
error An unexpected error occurred: "Unknown token: { line: 3, col: 2, type: 'INVALID', value: undefined } 3:2 in ~/tools/yarn.lock".
info If you think this is a bug, please open a bug report with the information provided in "~/tools/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```
remove yarn.lock and `yarn install`

```$ yarn run run:api 
yarn run v1.15.2
$ ./packages/api-cli/src/index.cjs
node:internal/modules/cjs/loader:928
  throw err;
  ^

Error: Cannot find module './cli.cjs'
Require stack:```

**Comment by jacogr** [comment]
Not sure why you are removing `yarn.lock` here - actually in the current master version, doing so will result in an outright failure. (Or at least doe for me after the recent bump to the latest version of yarn berry)

To upgrade dependencies, rather use `yarn upgrade-interactive`

**Comment by bostontrader** [comment]
I've had the same issue in several areas of the code.  The general problem that I've seen is an import statement is trying to import a file w/o an extension, such as ...

import  ... from './cli';

There _is_ a file named cli.ts but not cli.cjs.  I don't know the gory details about how import guesses which file to import, but it looks like by default it's looking for cli.cjs, which ain't there.  If I change the import statement to import './cli.ts' instead, then this works, even though I get other warnings about using a file name with extension.

I've seen and fixed about 10 examples of this and I'm sure there are a few more that I haven't found.  I am however unfortunately not familiar enough with this code to submit a pull-request.  Nevertheless, perhaps my experience will be useful for the next hapless soul to step in this.
