### ISSUE TITLE
error Command "run:signer" not found.

### ISSUE THREAD

**Issue by ThreeAndTwo** [polkadot-js/tools#241]
I use like demo command `yarn run signer submit --account 5GgkF3UEHj5A994bKcjiMwsAXn1WhcAvhYk2p9cXFx5a5DB5 --ws ws://127.0.0.1:9944 balances.transferKeepAlive 5CJrsXSJGVNxuBVyaXPLT7rVNWGckjXc7T8rCx5P3PUWEYxv 500000000000` is there anything wrong?

**Comment by jacogr** [comment]
run:signer 

See https://github.com/polkadot-js/tools/blob/master/package.json#L28

**Comment by ThreeAndTwo** [comment]
> run:signer
> 
> See https://github.com/polkadot-js/tools/blob/master/package.json#L28

thx~
