### ISSUE TITLE
Passing an array (Vec) of values as extrinsic parameter using the CLI

### ISSUE THREAD

**Issue by PierreBesson** [polkadot-js/tools#275]
I am trying to pass an array of values as parameters to an extrinsic submitted via the CLI but I don't find anything in the README about it.

This is the kind of command I would like to be able to run (not working):
```
polkadot-js-api --ws 'wss://rococo-rpc.polkadot.io' --sudo --seed XXX --tx.validatorManager.registerValidators Address1,Address2
```

This is what the operation looks like using Polkadot.JS UI:
![image](https://user-images.githubusercontent.com/513471/134659564-ae47eded-0372-4bb7-9086-c0bb80212a5a.png)

**Comment by jacogr** [comment]
The input is always treated as JSON, so the following should work -

```
'["Address1", "Address2"]'
```

**Comment by PierreBesson** [comment]
Thank you this works perfectly.
