### ISSUE TITLE
Cannot set validator preferences with api-client

### ISSUE THREAD

**Issue by weezy20** [polkadot-js/tools#370]
This problem has been frustrating me for a couple of days : 
I am trying to set validator prefs using the api-cli and this is what I've tried: 
```yarn run:signer submit --account .. staking.validate '[35, false]'  --ws ..```. 
 It always comes out to `0.0`. I've tried `"35"`, `35.0`, to no avail. It won't accept non-integer values which is fine. But it won't work with the integer either. With the gui setting this percentage is relatively straightforward, not with the api-cli. I've tried using both `signer submit` and `api-cli` for sending this transaction and it does get into the blockchain but unfortunately I don't see my commission percentage in there.

**Comment by jacogr** [comment]
`yarn run:signer submit --account .. staking.validate 35 false --ws ...`

No quotes. By adding the quotes you are turning it into a single parameter which is a non-number for the first value. The extrinsic needs 2 parameters, specify them separately.

**Comment by weezy20** [comment]
That gives another problem : Error: Extrinsic staking.validate expects 1 arguments, got 2.

**Comment by jacogr** [comment]
Ahhh, I see the issue. The `0.0` I'm assuming is what you see on the UI.

So the value for the staking is a perbill value, i.e. parts per billion. So 35 ends up as `35 / 1000000000` which is 0.00....0035%` in the display.

So for e.g. 1% it would be `10000000`, 3.5% would be `35000000`

**Comment by weezy20** [comment]
Yes! That's it. That seems to fix the issue. But still, why do you think this call requires a tuple when the other calls like `staking.bond` do fine with space separated arguments?

**Comment by jacogr** [comment]
Since it is validator prefs that are passed, and that is a structure, it need to go in struct format, i.e. something like `... '{ "commission": 35000, "blocked": false }' ...` or indeed you can pass a tuple with the values in order, i.e. `... '[35000, false]' ...` where the first would fill in the commission, the second blocked on that structure.

**Comment by weezy20** [comment]
One final question and we can close this issue. I don't understand the second `"blocked"` parameter. What does it do?

**Comment by jacogr** [comment]
`blocked = true` disallows any nominations to that validator.

**Comment by weezy20** [comment]
Thank you for your prompt help @jacogr. Appreciate it.
