### ISSUE TITLE
Setting `custom_type` for extrinsics (session.setKeys) doesn't modify arguments expected

### ISSUE THREAD

**Issue by anthonyra** [polkadot-js/tools#430]
* **I'm submitting a ...**

  - [x] Bug report
  - [ ] Feature request
  - [ ] Support request
  - [ ] Other

* **What is the current behavior and expected behavior?**

I'm attempting to use the Docker Image as a sidecar running locally with a node. The intent is to use the `session.setKeys` but the chain uses a custom type with respect to this command.

custom_types.json
```json
{
  "Keys": "SessionKeys2",
  ...
}
```

Below is the docker run command that I'm using
```
docker run \
--name polkadotjs \
--network host \
--volume <custom_volume> \
jacogr/polkadot-js-tools \
api \
--types custom_types.json \
--seed "//Alice" \
tx.session.setKeys $AURA $GRAN 0x00
```

It's able to connect to the local node but returns the following error
```
Error: Extrinsic session.setKeys expects 2 arguments, got 3.
    at extrinsicFn (/usr/lib/node_modules/@polkadot/api-cli/node_modules/@polkadot/types/cjs/metadata/decorate/extrinsics/createUnchecked.js:24:13)
    at decorated (/usr/lib/node_modules/@polkadot/api-cli/node_modules/@polkadot/api/cjs/base/Decorate.js:543:22)
    at makeTx (/usr/lib/node_modules/@polkadot/api-cli/cjs/runcli.js:188:16)
    at main (/usr/lib/node_modules/@polkadot/api-cli/cjs/runcli.js:226:12)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

My understanding is that with passing in the custom types on API construction it will know that it needs 2 session keys instead of the default. However, the arguments are expecting 2 and when using the Polkadotjs App it needs 3 which is what I expect to pass in here.

As in the Polkadotjs UI is showing the need for 3 arguments.

* **What is the motivation for changing the behavior?**

I'm not sure if behavior needs to change. I'm curious if I just need to pass in the session key as returned by the `session.rotateKeys` response and with the custom type accepted will encode the response differently? Or it could very well be a bug.

* **Please tell us about your environment:**

  - Version:
  - Environment:

    - [x] Node.js
    - [ ] Browser
    - [x] Other (limited support for other environments) - Docker

  - Language:

    - [ ] JavaScript
    - [x] TypeScript (include tsc --version)
    - [ ] Other

**Comment by jacogr** [comment]
The setKeys would expect to be in the form -

```
setKeys(<keys>, <proof>)
```

So in this case ensure that you pass 1 argument for the `<keys>`, i.e. a single hex string with everything concatenated. If you have a list of addresses, the `<keys>` is a tuple, so the tuple form _should_ also work, i.e.

```
...
api \
--types custom_types.json \
--seed "//Alice" \
tx.session.setKeys "[\"$AURA\", \"$GRAN\"]" 0x00
```
