### ISSUE TITLE
Docker metadata failing

### ISSUE THREAD

**Issue by wilwade** [polkadot-js/tools#455]
* **I'm submitting a ...**

  - [x] Bug report

* **What is the current behavior and expected behavior?**

Expected and prior (to the v10 release?) `docker run --pull always --network host jacogr/polkadot-js-tools ws://localhost:9946 ws://localhost:9944` would work when running it with two nodes locally.

Current: 
```
/usr/bin/polkadot-js-metadata-cmp: line 1: import: command not found
/usr/bin/polkadot-js-metadata-cmp: line 2: import: command not found
/usr/bin/polkadot-js-metadata-cmp: line 3: import: command not found
/usr/bin/polkadot-js-metadata-cmp: line 4: import: command not found
/usr/bin/polkadot-js-metadata-cmp: line 5: import: command not found
/usr/bin/polkadot-js-metadata-cmp: line 6: import: command not found
/usr/bin/polkadot-js-metadata-cmp: line 7: import: command not found
/usr/bin/polkadot-js-metadata-cmp: line 8: syntax error near unexpected token `('
/usr/bin/polkadot-js-metadata-cmp: line 8: `const [ws1, ws2] = yargs(hideBin(process.argv)).demandCommand(2).argv._;'
```

  - Version: latest docker image
  - Environment: Docker
  
  
Guess: This has something to do with the latest version update (v10.0.1) and move to es modules.

### Additional Tests

(Tested on an M1 mac)

Actions `v0.52.9` Works:
- git checkout v0.52.9
- yarn
- yarn run:metadata
- Success ✅ 
- `./docker/build.sh build`
- Build Success ✅ 
- `docker run docker.io/library/polkadot-js-tools metadata`
- Success ✅ 

Actions `v0.53.1` FAIL:
- git checkout v0.53.1
- yarn
- yarn run:metadata
- Success ✅ 
- `./docker/build.sh build`
- Build Success ✅ 
- `docker run docker.io/library/polkadot-js-tools metadata`
- FAIL ❌  (Same error as above)

**Comment by wilwade** [comment]
@IkerAlus 

What version of Nodejs and OS are you on?

On Mac (M1) 13.2.1 with Nodejs v16.14.0 it works, so haven't been able to reproduce outside of Docker, but Docker is using v14 Nodejs.

**Comment by IkerAlus** [comment]
@wilwade I got the error with Nodejs v16.14.2 and Mac 12.3.1

**Comment by IkerAlus** [comment]
@wilwade Indeed, v0.53.4 installed correctly in my system, thanks for the suggestion!

**Comment by wilwade** [comment]
🎉
