### ISSUE TITLE
Tag published docker image with release version

### ISSUE THREAD

**Issue by demisx** [polkadot-js/tools#456]
* **I'm submitting a ...**

  - [ ] Bug report
  - [X] Feature request
  - [ ] Support request
  - [ ] Other

* **What is the current behavior and expected behavior?**
The image published at https://hub.docker.com/r/jacogr/polkadot-js-tools is not currently tagged with release version. It is always published as `latest`, thus overwriting the previously published version. I would expect each released image to be tagged with the corresponding release tag from https://github.com/polkadot-js/tools/releases

* **What is the motivation for changing the behavior?**
We need to be able to pin image to a particular version, so upgrades to a new version happened in a controlled planned manner. Otherwise, a new update can break current process like it happened in #455.

**Comment by jacogr** [comment]
Sadly this is very unlikely to happen without any PRs provided. There is just no extra capacity to apply to this.

**Comment by wilwade** [comment]
@jacogr Understandable. PR thrown up (just one line in the end) #459
